// src/components/ConflictBanner.tsx
/**
 * 文件被外部修改且本会话有未保存修改时的冲突横幅。
 * 由 EditorPane 在 session.conflict 时渲染;reloadFromDisk / keepLocal 二选一。
 */
import type { DocumentSession } from "../lib/files/document";
import { useStoreVersion } from "../lib/react/reactive";

export function ConflictBanner({ session }: { session: DocumentSession }) {
  useStoreVersion(session);
  return (
    <div className="banner conflict">
      <span className="text">⚠️ 文件已被外部修改</span>
      <span className="actions">
        <button className="btn" onClick={() => void session.reloadFromDisk()}>
          重新加载
        </button>
        <button className="btn primary" onClick={() => void session.keepLocal()}>
          保留当前版本(覆盖)
        </button>
      </span>
    </div>
  );
}

// src/components/ConflictBanner.svelte
<script lang="ts">
  import type { DocumentSession } from "../lib/files/document.svelte";

  let { session }: { session: DocumentSession } = $props();
</script>

<div class="banner conflict">
  <span class="text">⚠️ 文件已被外部修改</span>
  <span class="actions">
    <button class="btn" onclick={() => void session.reloadFromDisk()}>重新加载</button>
    <button class="btn primary" onclick={() => void session.keepLocal()}>保留当前版本(覆盖)</button>
  </span>
</div>

<style>
  .banner.conflict {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 8px 14px;
    border-radius: var(--r-card);
    background: var(--panel);
    border: 1px solid var(--acc);
    box-shadow: var(--shadow-md);
    font-size: 13px;
    animation: rd-pop var(--dur-move) var(--ease-out);
  }

  .text {
    color: var(--acc);
    white-space: nowrap;
  }

  .actions {
    display: flex;
    gap: 8px;
  }
</style>
