// src/components/NormalizeNotice.tsx
/**
 * roundtrip 无损性提示:保存时会被规范化排版(渲染不变)。
 * 由 EditorPane 在 !lossless 时渲染;"不再提醒"写入设置。
 */
import type { DocumentSession } from "../lib/files/document";
import { settingsStore } from "../lib/settings/settingsStore";
import { useStoreVersion } from "../lib/react/reactive";

export function NormalizeNotice({ session }: { session: DocumentSession }) {
  useStoreVersion(settingsStore);
  useStoreVersion(session);

  if (settingsStore.settings.hideRoundtripNotice || session.lossless) return null;

  return (
    <div className="banner normalize">
      <span className="text">此文件含保存时会被规范化的写法(渲染效果不变,仅源码排版统一)</span>
      <span className="actions">
        <button className="btn" onClick={() => settingsStore.update("hideRoundtripNotice", true)}>
          不再提醒
        </button>
      </span>
    </div>
  );
}

// src/components/NormalizeNotice.svelte
<script lang="ts">
  import type { DocumentSession } from "../lib/files/document.svelte";
  import { settingsStore } from "../lib/settings/settingsStore.svelte";

  let { session }: { session: DocumentSession } = $props();
</script>

{#if !settingsStore.settings.hideRoundtripNotice && !session.lossless}
  <div class="banner normalize">
    <span class="text">此文件含保存时会被规范化的写法(渲染效果不变,仅源码排版统一)</span>
    <span class="actions">
      <button class="btn" onclick={() => settingsStore.update("hideRoundtripNotice", true)}>不再提醒</button>
    </span>
  </div>
{/if}

<style>
  .banner.normalize {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 8px 14px;
    border-radius: var(--r-card);
    background: var(--panel);
    border: 1px solid var(--line2);
    box-shadow: var(--shadow-md);
    font-size: 12.5px;
    color: var(--mut);
    animation: rd-pop var(--dur-move) var(--ease-out);
  }

  .actions {
    display: flex;
    gap: 8px;
  }
</style>
